### ISSUE TITLE
Can Cursor Lock and NWNLogRotator coexist together in harmony?

### ISSUE THREAD

**Issue by NWN1star** [noblesigma/NWNLogRotator#14]
Got an issue I'm trying to get CursoLock to work with NWNLogRotator which I like for taking Logs of Neverwinter Nights 1. Both of these programs are set up to use NWNmain.exe. I can get each working separately but they won't work together. I tried Cursor Lock in both fullscreen mode and Windows interior mode. Do you have any idea if this would even be possible to do?  Here Is a video of the NWNLogRotator

https://youtu.be/Myivw84ONJQ

https://neverwintervault.org/project/nwn1/other/tool/nwnlogrotator

**Comment by noblesigma** [comment]
Unfortunately, there doesn't seem to be a way currently. 

A solution is possible albeit a bit hacky. Would involve saving the logs regardless of the launch feature optionally. When I get time to look more into it I'll try it out.

**Comment by NWN1star** [comment]
Thanks, for even looking into it.

**Comment by noblesigma** [comment]
After looking into it, apparently it's already possible.

Make sure you have everything configured. Then start the game, in the app, bottom right it will go from nwmain is inactive-->active-->inactive. 

On the state change of active->inactive, it should generate a log.

If it does not, try to configure more of the options even if you're not using all of them. Please let me know if this doesn't help.

**Comment by NWN1star** [comment]
Ok, I guess I wasn't too clear on what the problem was. Yes, I can get a log to work in NWNlogrotator, as I stated it creates logs and I got that working so that is not the main issue and maybe this isn't the best place to find the solution to the problem. 

The issue is Cursor Lock won't lock the Screen when NWNLog is being used. Cursor lock needs to access NWmain.exe as well to lock the screen and so does NWNLog Rotator. The Cursor lock will allow you to lock the mouse in the window or prevent the mouse from leaving it and going into a secondary monitor on your desktop while you're playing a video game. 

I tried creating log rotator which is placed in my C: drive pointed at NWmain.exe in another folder on that drive and then using that link it created and trying to have cursor lock open it in its "program options" field, then under "standard options" check-marked the "lock Region/ Window Interior and Force Lock options which locks the mouse in windowed mode so you can't accidentally close the window while playing the game. I also have HotKeys set up for the keyboard key L  so I can "toggle" in and out of the locked window which allows my mouse to get back to my desktop. When I point the Cursor lock to the NWNLogRotator version of NWmain.exe on my C: drive, LogRotator can't find NWmain.exe at the bottom of its screen and so it won't log anything but the window will lock the mouse correctly. When clicking on the log rotator executable on the C: drive without cursor lock involved it will work and log the chats as expected. 

I did try launching Cursor Lock/ Nwmain.exe shortcut that CursorLock makes from the NWNlogRotator Launcher Client button but all it does is open the CursorLock setup program and not Cursorlock/ NWmain.exe combo link to start the game and NWN Log Rotator will not see Nwmain.exe and make it active doing it this way.

I did have some codes popping up along the way that I had to raise inheritance in Windows and I gave the links and Executables admin  and full control access to no avail. 

Well, sorry for the delayed response and lack of clarity, hope this makes more sense.

**Comment by noblesigma** [comment]
Don't launch the game with NWNLogRotator. Please try this

**Comment by NWN1star** [comment]
Ok, Thanks for your heLp, I think it shouLd probaby work now, but you shouLd have inLcuded information about the options "Start Cient automaticay when auncher opens", which I had checked. I asLo turned off the "CLose Launcher automaticaLLy when cLient cLoses that I had checked right of the bat. I didn't reaLize the rammifications of what this wouLd do when I Later started to try to incorporated both programs at the same time. 
It wouLd aLso be a nice touch to have a heLp fiLe on the functions of each and how they couLd be used. Is there one? If there is I must of missed it. 

What is SiLent mode? Why wouLd you want to save a Log on Launch?, FiLter Lines?

Now ALL I have to do is figure out why my Lower case L is not working on my keyboard LOL.

**Comment by noblesigma** [comment]
Q:What is SiLent mode?
Silent mode doesn't pop up when logs generate.

Q: Why wouLd you want to save a Log on Launch?
A: https://github.com/noblesigma/NWNLogRotator/issues/13

Q:  FiLter Lines?
In case some spam occurs on a server you play on that you want to omit you can add it here.

Q: Could it be possible to generate a log without exiting out of the game?
A: Yes, but only through "Run Once"
